# Generated by Django 5.1 on 2024-08-26 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion_Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProductosOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('fecha_creacion', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadoorden')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mesa')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estacion_trabajo')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadoproductosorden')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurante')),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurante'),
        ),
        migrations.AddField(
            model_name='estadoproductosorden',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurante'),
        ),
        migrations.AddField(
            model_name='estadoorden',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurante'),
        ),
        migrations.CreateModel(
            name='EstadoBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurante')),
            ],
        ),
        migrations.AddField(
            model_name='estacion_trabajo',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurante'),
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField()),
                ('total', models.IntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadoboleta')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orden')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orden_productos')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estacion_trabajo')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurante')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trabajador'),
        ),
    ]
