# Generated by Django 5.1 on 2024-08-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='correo',
            field=models.EmailField(default='a1a@a1a.com', max_length=50),
        ),
    ]
