# Generated by Django 5.1 on 2024-08-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trabajador_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='correo',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
